#!/usr/bin/env ruby

require 'fileutils'
#
folder = ARGV[0]

files = Dir[folder+"/*.csv"]
output_dir = "./output/" + folder.split("/").last
file_index = 1
FileUtils.mkdir_p output_dir

files.each do |file|
  puts "processing file #{file_index} of #{files.length}: #{file}"
  destination = File.join(output_dir, File.basename(file).gsub(".csv", ".json"))
  unless File.exists?(destination) && File.size(destination) > 0
    `cat "#{file}" | ./csv_to_geo_yaml | ./fence_builder --fence-size 0.062 > "#{destination}"`
  end
  file_index += 1
end

